# Generated by Django 4.1.5 on 2023-05-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=1000)),
                ('votes', models.IntegerField(max_length=2000)),
                ('picture', models.ImageField(default='profilepic.jpg', upload_to='candidate_pictures')),
            ],
        ),
    ]
