# Generated by Django 4.1.5 on 2023-05-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectionCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='votes',
            field=models.IntegerField(),
        ),
    ]
