# Generated by Django 4.1.5 on 2023-05-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectionCode', '0002_alter_candidates_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
