# Generated by Django 4.1.5 on 2023-05-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElectionCode', '0003_alter_candidates_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidates',
        ),
    ]
