# Generated by Django 4.1.5 on 2023-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_questions_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=200)),
                ('survey_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
