# Generated by Django 4.1.5 on 2023-05-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answers', models.CharField(max_length=200)),
                ('identity', models.CharField(max_length=7)),
            ],
        ),
    ]
