# Generated by Django 4.1.5 on 2023-06-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='answers',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question',
        ),
    ]
