# Generated by Django 4.1.5 on 2023-06-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_rename_answers_questions_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identity', models.CharField(max_length=50)),
                ('questions', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
